import clsx from 'clsx';

import type { Metadata } from 'next';
import { Inter, Unbounded } from 'next/font/google';
import './globals.css';

import Header from '@/layout/Header';
import Footer from '@/layout/Footer/Footer';

import StoreProvider from './StoreProvider';

export const metadata: Metadata = {
  title: 'BuildHub',
  description: 'Generated by create next app',
};

const unbounded = Unbounded({
  subsets: ['cyrillic', 'latin'],
  weight: ['500', '700'],
  display: 'swap',
  variable: '--font-unbounded',
});

const inter = Inter({
  subsets: ['cyrillic', 'latin'],
  weight: ['300', '400', '500', '700', '800'],
  display: 'swap',
  variable: '--font-inter',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={clsx(
            unbounded.variable,
            inter.variable,
            'flex h-full min-h-screen flex-col overflow-x-hidden'
          )}
        >
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </body>
      </StoreProvider>
    </html>
  );
}
